# Cloudflare Worker 配置文件

name = "wechat-customer-service"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
name = "wechat-customer-service"
# 微信企业号配置
WECHAT_CORP_ID="ww79a3e96fb2c3ed1b"
WECHAT_KF_SECRET="SAZIpi716-4-Z0QqVhvhIcwq_aXhf9W2f-Ap4PImqNc"
WECHAT_KF_TOKEN="1"
WECHAT_KF_ENCODING_AES_KEY="2"

# 加密服务配置（由于 CF Worker CRYPTO 兼容性问题，需要单独部署）
CRYPTO_SERVICE_URL="3"

# OpenAI API 配置
OPENAI_API_KEY="sk-DIQ0xp6cSgYhgq1OF90b2072457948A2A03a77C031Cd0147"
OPENAI_BASE_URL="https://one.941103.xyz/"
OPENAI_MODEL="gemini-2.5-pro"
OPENAI_TIMEOUT=30000
# OPENAI_ORGANIZATION=org-your-org-id
# OPENAI_PROJECT=proj-your-project-id

# 系统提示词配置
SYSTEM_PROMPT="your are helpful assistant, reply in chinese, and reply in plain text format, text length should be less than 10240 characters" 


# KV存储配置（用于持久化对话历史）
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "77cd8ae41e1545b5810bb56d4d7f05bf"
preview_id = ""

# KV存储配置（用于消息处理状态跟踪）
[[kv_namespaces]]
binding = "MESSAGE_TRACKER"
id = "273de818994d42ecbf66eca51ca92b40"
preview_id = ""